apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: test-mvp-component-othe
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: var_name
          value: test
        image: quay.io/redhat-appstudio-qe/test-images@sha256:8834cde7f9ad56ae08126e1046ae7aa937c1355290ca7b077996529b484c8076
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
